markdown: kramdown
highlighter: rouge
title: Robin Piedeleu
description: Postdoctoral Researcher in Computer Science at UCL
url: piedeleu.com
baseurl: ''
author:
  name: Robin Piedeleu
email: robin.piedeleu@gmail.com
twitter: rwolffoot

paginate: 5
paginate_path: '/blog/page:num'
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
sidebar_home_link: true
