markdown: kramdown
highlighter: rouge
title: Robin Piedeleu
description: UCL
url: piedeleu.com
baseurl: ''
author:
  name: Robin Piedeleu
email: r.piedeleu@ucl.ac.uk
twitter: rwolffoot

paginate: 5
paginate_path: '/blog/page:num'
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
sidebar_home_link: true
